name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - staging  # or the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js application
        run: yarn build
        env:
          CI: false

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Configure Firebase Target
        run: |
          firebase target:apply hosting documentation-staging documentation-staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          region: us-west1
          projectId: trume-staging-419120
          target: documentation-staging
          token: ${{ secrets.FIREBASE_TOKEN }}
